[package]
name = "syn-zeug"
version = "0.1.0"
authors = ["Brooks J Rady <b.j.rady@gmail.com>"]
edition = "2021"

[dependencies]
bio = "0.40"
once_cell = "1.10"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.24", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
iai = "0.1"
pprof = { version = "0.7", features = ["criterion", "flamegraph"] }

[[bench]]
name = "criterion"
harness = false

[[bench]]
name = "iai"
harness = false
