[package]
name = "biobox"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bio = "1.1.0"
syn-zeug = { path = "../syn-zeug" }
getrandom = { version = "0.2.8", features = ["js"] }
wasm-bindgen = "0.2.83"
serde-wasm-bindgen = "0.4.5"
serde = "1.0.150"
