[package]
name = "biobox"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bio = { path = "../rust-bio" }
syn-zeug = { path = "../syn-zeug" }
getrandom = { version = "0.2.7", features = ["js"] }
wasm-bindgen = "0.2.82"
serde-wasm-bindgen = "0.4.3"
serde = "1.0.144"
