[package]
name = "biobox"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
syn-zeug = { path = "../syn-zeug" }
getrandom = { version = "0.2.6", features = ["js"] }
wasm-bindgen = "0.2.80"
serde-wasm-bindgen = "0.4.3"
